"""GetAround — car rental price prediction API.

Serves the regression pipeline trained in `model/` behind a small HTTP API so
that any internal service can request a price without shipping scikit-learn or
knowing how the features were encoded.

Endpoints
---------
GET  /         service metadata and a pointer to the docs
GET  /health   liveness probe, reports whether the model is loaded
POST /predict  price a single car
GET  /docs     interactive OpenAPI documentation (generated by FastAPI)

Design notes
------------
* The serialised artifact is the **full pipeline** (preprocessing + estimator).
  The API therefore does no encoding of its own: the fitted scaler and encoder
  travel inside the .joblib file and apply exactly as they did at training time. There
  is no second implementation to drift out of step (train/serving skew).
* The model is loaded once at import time and kept in memory; requests only run
  inference.
* Unknown categorical values are rejected with a 422 rather than silently
  scored. The encoder is fitted with `handle_unknown="ignore"`, which keeps the
  service from crashing but would otherwise return a plausible-looking price for
  an input the model never saw (e.g. "Citroen" without the diaeresis).
  If the encoder cannot be located in the artifact, that guard is disabled and
  the service still starts, logging a warning. Refusing to start would be the
  right call for a model fetched at runtime, where the artifact is a variable;
  here it ships inside the image and is covered by the tests, so the branch is
  unreachable in practice and a boot-time failure would guard against nothing.
* The model file is baked into the container image (unlike if we used a model registry)
  Updating the served model therefore means rebuilding and redeploying the image — 
  a deliberate trade-off that keeps the API independent from the tracking infrastructure —
  we would opt for the model registry if the model was retrained weekly on fresh data.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

import joblib
import pandas as pd
import sklearn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, ConfigDict, Field
from sklearn.preprocessing import OneHotEncoder

# This module is the entry point, so it configures logging for the entire process
# /program. We lower to INFO the threshold at which logs/messages are displayed 
# so that we can see "Loaded model from …" line below — the only record of which 
# artifact was loaded, and under which scikit-learn version, at the one moment 
# that matters: before the service accepts its first request.
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

# We tell the API where to find the model file: in the MODEL_PATH environment variable 
# if someone set it, otherwise the fallback is the file sitting just next to the app file.
MODEL_PATH = Path(os.getenv("MODEL_PATH", Path(__file__).parent / "model.joblib"))

# At module level, so this runs once at startup rather than on every request.
# It also means that a missing or unreadable artifact would prevent the container 
# from starting, instead of letting it accept traffic it cannot serve. 
model = joblib.load(MODEL_PATH)
logger.info("Loaded model from %s (scikit-learn %s)", MODEL_PATH, sklearn.__version__)


def _known_categories(pipeline) -> dict[str, list[str]]:
    """Return the categories each categorical column was fitted on.

    Read back from the fitted pipeline / OneHotEncoder rather than hard-coded,
    so the values the API accepts always match the model actually being served.
    They cannot fall out of sync, since they are extracted from it.

    Returns an empty dict if the encoder cannot be located. That disables the
    guard in `_reject_unknown_categories` — which iterates over this dict and
    therefore rejects nothing — without affecting predictions: the pipeline is
    untouched and still encodes every categorical column as it always did.
    """
    def disabled() -> dict[str, list[str]]:
        # Two exits below reach this state; naming it keeps the warning in one
        # place and marks both returns as degraded rather than normal.
        logger.warning(
            "Could not locate a fitted OneHotEncoder inside %s — unknown-category "
            "validation is disabled; predictions are unaffected.",
            MODEL_PATH,
        )
        return {}

    try:
        transformers = pipeline.named_steps["preprocessor"].transformers_
    except (AttributeError, KeyError):
        # Reached only if the artifact is not the pipeline this API expects: no
        # step named "preprocessor", or a step that is not a ColumnTransformer.
        # The service still starts and still prices known inputs correctly — it
        # just loses the unknown-category guard.
        return disabled()

    # Matched on type, not on the "cat" step name: renaming that step in
    # train.py would otherwise disable validation here without any error.
    for _, transformer, columns in transformers:
        if isinstance(transformer, OneHotEncoder):
            # Compared as strings because that is what arrives over JSON.
            return {
                column_name: sorted(map(str, categories))
                for column_name, categories in zip(columns, transformer.categories_)
            }

    return disabled()


# Run once at startup rather than inside predict(): the model never changes, so
# its categories never change either.
KNOWN_CATEGORIES = _known_categories(model)


# Not decoration: FastAPI renders these into the /docs page, so the API documents 
# itself rather than relying on a separate file.
app = FastAPI(
    title="GetAround — Car Rental Price Prediction API",
    description=(
        "Predicts the daily rental price of a car from its characteristics. "
        "See **/docs** for an interactive console."
    ),
    version="1.0.0",
)


class CarFeatures(BaseModel):
    """Input schema: one car.

    Field names must match the column names used at training time — the
    pipeline looks columns up by name. Numeric bounds are declared here so that
    impossible values are rejected before they reach the model.
    """

    # `model_key` collides with Pydantic v2's protected `model_` namespace;
    # clearing the namespace avoids a warning on every import.
    model_config = ConfigDict(protected_namespaces=())

    # `...` marks the field required. The bounds mirror the thresholds used to
    # clean the training data, plus a engine_power ceiling it never needed: input
    # validation may be stricter than cleaning, never looser.
    model_key: str = Field(..., examples=["Citroën"])
    mileage: int = Field(..., ge=0, le=1_000_000, examples=[140000])
    engine_power: int = Field(..., gt=0, le=1000, examples=[100])
    fuel: str = Field(..., examples=["diesel"])
    paint_color: str = Field(..., examples=["black"])
    car_type: str = Field(..., examples=["sedan"])
    private_parking_available: bool = Field(..., examples=[True])
    has_gps: bool = Field(..., examples=[True])
    has_air_conditioning: bool = Field(..., examples=[False])
    automatic_car: bool = Field(..., examples=[False])
    has_getaround_connect: bool = Field(..., examples=[True])
    has_speed_regulator: bool = Field(..., examples=[True])
    winter_tires: bool = Field(..., examples=[False])


class PredictionOut(BaseModel):
    """Response schema. Declared so the contract is documented and enforced."""

    rental_price_per_day: float


def _reject_unknown_categories(payload: dict) -> None:
    """Raise 422 when a categorical value was never seen during training.

    Runs on every request, against the list built once at startup. Without it,
    `handle_unknown="ignore"` would encode an unseen value as all-zeros and the
    model would return a confident, wrong price.
    """
    # Iterates over KNOWN_CATEGORIES, not over the payload: those four columns
    # are the only ones with a closed list of valid values (numeric fields are
    # bounded by the schema instead). An empty dict here therefore checks
    # nothing — that is how the guard degrades.
    unknown = {
        column_name: payload[column_name]
        for column_name, allowed_values in KNOWN_CATEGORIES.items()
        if column_name in payload
        and str(payload[column_name]) not in allowed_values
    }

    # Nothing to report: return None and let predict() carry on. This is the
    # normal path — the raise below is the exception, not the rule.
    if not unknown:
        return

    # Same 422 and same detail shape FastAPI already returns for schema errors,
    # so a client that handles those needs no extra branch for these.
    raise HTTPException(
        status_code=422,
        # One dict per offending column, all returned together: a client who
        # got both the brand and the fuel wrong sees both errors at once,
        # instead of fixing one and discovering the next on the retry.
        detail=[
            {
                "loc": ["body", column_name],
                # !r quotes the value, so a stray space or accent is visible.
                "msg": f"Unknown value {value!r}; the model was not trained on it.",
                "type": "value_error.unknown_category",
                "allowed_values": KNOWN_CATEGORIES[column_name],
            }
            for column_name, value in unknown.items()
        ],
    )


# The decorator registers the route: FastAPI records path + verb in its routing
# table at import time, and calls the function when a matching request arrives.
# The returned dict is serialised to JSON automatically.
@app.get("/")
def home() -> dict:
    """Service metadata. Avoids a bare 404 for anyone opening the root URL."""
    return {
        "message": "GetAround car rental price prediction API.",
        "documentation": "/docs",
        "predict_endpoint": "POST /predict",
    }


@app.get("/health")
def health() -> dict:
    """Liveness probe.

    Reports the loaded scikit-learn version alongside the model state: a
    `.joblib` only deserialises reliably under the version that wrote it, so
    this is the first thing to check when a deployment misbehaves.
    """
    return {
        "status": "ok",
        # 'model is not None' is always true today, since a failed load stops 
        # the container from starting and this endpoint would never answer. 
        # Kept because it documents what is being asserted, and would carry 
        # real information if the model were ever fetched from a registry.
        "model_loaded": model is not None,
        "sklearn_version": sklearn.__version__,
    }


# POST rather than GET: the caller sends 13 values to be processed, and thirteen
# query parameters in a URL would be unreadable. response_model declares what
# comes back, so the response shape cannot change without editing that line.
@app.post("/predict", response_model=PredictionOut)
def predict(car: CarFeatures) -> dict:
    """Predict the daily rental price of a single car.

    Raw features are passed straight to the pipeline: the scaler and encoder are
    embedded in the artifact and applied exactly as they were during training,
    which rules out train/serving skew.
    """
    payload = car.model_dump()

    # Checked before inference: the model would happily score an unknown brand
    # as all-zeros and return a plausible price.
    _reject_unknown_categories(payload)

    # scikit-learn always takes a table of rows and columns, so one car still
    # goes in as a one-row table. It must be a DataFrame rather than a plain
    # array: the pipeline finds each feature by column name, which is why those
    # names have to match the ones used at training time.
    features = pd.DataFrame([payload]) # a list that contains a dict

    # predict() answers one row per input row, so [0] pulls out the only one.
    # float() converts numpy's float64 into a plain Python float, which is what
    # JSON can encode.
    prediction = float(model.predict(features)[0])

    # Rounded to the cent: the response is a price, and with a mean absolute
    # error around 11 € more decimals would be false precision.
    return {"rental_price_per_day": round(prediction, 2)}
